/*!CK:2332421225!*//*1431921589,*/

if (self.CavalryLogger) { CavalryLogger.start_js(["VLifm"]); }

__d("AdsInsightsSummaryLabels",[],function(a,b,c,d,e,f){b.__markCompiled&&b.__markCompiled();e.exports={};},null);
__d("AttachmentCTA",["Style"],function(a,b,c,d,e,f,g){b.__markCompiled&&b.__markCompiled();var h=10,i={init:function(j){var k=j.parentNode,l=Math.max(k.scrollHeight-j.scrollHeight-h*2,0);g.set(j,'margin-top',l+'px');}};e.exports=i;},null);
__d("AbstractCheckboxInput.react",["React","cx","invariant","joinClasses"],function(a,b,c,d,e,f,g,h,i,j){b.__markCompiled&&b.__markCompiled();var k=g,l=k.PropTypes,m=g.createClass({displayName:"AbstractCheckboxInput",propTypes:{tooltip:l.string},render:function(){i(!this.props.children||this.props.children.length===0);var n=j(this.props.className,"_kv1"),o=g.createElement("input",g.__spread({},this.props,{className:null,type:"checkbox"}),undefined);return (g.createElement("label",{className:n},o,g.createElement("span",{"data-hover":this.props.tooltip?'tooltip':null,"aria-label":this.props.tooltip})));}});e.exports=m;},null);
__d("XUICheckboxInput.react",["AbstractCheckboxInput.react","React","cx","joinClasses"],function(a,b,c,d,e,f,g,h,i,j){b.__markCompiled&&b.__markCompiled();var k=h.createClass({displayName:"XUICheckboxInput",render:function(){return (h.createElement(g,h.__spread({},this.props,{className:j(this.props.className,"_55sg")}),(void 0)));}});e.exports=k;},null);
__d("getSafeBodyFromHTML",["UserAgent"],function(a,b,c,d,e,f,g){b.__markCompiled&&b.__markCompiled();var h=g.isBrowser('IE <= 9');function i(j){var k,l=null;if(!h&&document.implementation&&document.implementation.createHTMLDocument){k=document.implementation.createHTMLDocument('foo');k.documentElement.innerHTML=j;l=k.getElementsByTagName('body')[0];}return l;}e.exports=i;},null);
__d("GiftCredits",["AsyncRequest","Dialog","URI"],function(a,b,c,d,e,f,g,h,i){b.__markCompiled&&b.__markCompiled();var j={dialog:null,callback:null,purchaseLock:false,purchaseLockExpiryThreshold:5000,purchaseLockTimeoutId:null,getPurchaseCreditPrompt:function(k,l,m,n){j.main(k,null,null,null,m,null,null,null,'BuyCredits',{},n);},redeemGiftcard:function(k,l,m){var n=new i(document.location).setPath('/giftcards').toString();j.main(k,null,null,n,null,null,null,null,l,{},m);},getPrompt:function(k,l,m,n,o,p,q,r,s,t,u,v,w,x,y,z,aa,ba,ca,da,ea,fa,ga,ha){j.main(k,l,m,n,o,p,q,r,s,t,u,v,w,x,y,z,aa,ba,ca,da,ea,fa,ga,ha);},main:function(k,l,m,n,o,p,q,r,s,t,u,v,w,x,y,z,aa,ba,ca,da,ea,fa,ga,ha){if(j.isPurchaseLocked())return false;j.setPurchaseLock(true);var ia={_path:'pay',method:'pay',display:'async',app_id:k,receiver:l,api_key:q,credits_purchase:x,action:s,next:n,dev_purchase_params:JSON.stringify(t),additional_params:JSON.stringify(u),order_info:JSON.stringify(m),product:v,package_id:w,request_id:y,sdk:z,quantity:aa,quantity_min:ba,quantity_max:ca,test_currency:da,pricepoint_id:ea,user:fa,user_hash:ga,ingame_gift_data:ha},ja=new g().setURI('/fbml/ajax/dialog/').setData(ia).setMethod('GET').setReadOnly(true).setStatusElement('commerce_get_more_loading');j.callback=o;j.dialog=new h().setAsync(ja).setModal(true).setCloseHandler(function(ka){j.setPurchaseLock(false);o(ka);}).show();},isPurchaseLocked:function(){return j.purchaseLock;},setPurchaseLock:function(k){j.purchaseLock=k;if(k){j.purchaseLockTimeoutId=setTimeout(function(){j.setPurchaseLock(false);},j.purchaseLockExpiryThreshold);}else clearTimeout(j.purchaseLockTimeoutId);return true;}};e.exports=j;},null);
__d("legacy:giftcredits",["GiftCredits"],function(a,b,c,d){b.__markCompiled&&b.__markCompiled();a.GiftCredits=b('GiftCredits');},3);
__d("CanvasResizer",["createArrayFromMixed","CSS","DOMEventListener","Vector"],function(a,b,c,d,e,f,g,h,i,j){b.__markCompiled&&b.__markCompiled();var k;function l(){var n,o=document.documentElement;if(window.innerHeight){n=window.innerHeight;}else if(o&&o.clientHeight){n=o.clientHeight;}else n=document.body.clientHeight;for(var p=0;p<k.length;p++){var q=k[p];if(!h.hasClass(q,'noresize')){var r=j.getElementPosition(q,'document').y,s=n-r;q.style.height=s/(k.length-p)+'px';}}}i.add(window,'resize',l);var m={smartSizingFrameAdded:function(){k=[];var n=g(document.getElementsByTagName('iframe'));n.forEach(function(o){if(h.hasClass(o,'smart_sizing_iframe')&&!h.hasClass(o,'noresize')){h.removeClass(o,'canvas_iframe_util');k.push(o);}});l();}};e.exports=m;},null);